info: History mask: 4294967295
gem5 has encountered a segmentation fault!

--- BEGIN LIBC BACKTRACE ---
build/X86/gem5.opt(+0xa77e50)[0x5586225e9e50]
build/X86/gem5.opt(+0xa8c1f5)[0x5586225fe1f5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x143c0)[0x7ff0ead253c0]
build/X86/gem5.opt(+0x978a4c)[0x5586224eaa4c]
build/X86/gem5.opt(+0x978dcf)[0x5586224eadcf]
build/X86/gem5.opt(+0x66eb4a)[0x5586221e0b4a]
build/X86/gem5.opt(+0x4d495f)[0x55862204695f]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8748)[0x7ff0eafdc748]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyObject_MakeTpCall+0xab)[0x7ff0eafdcb2b]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8df0)[0x7ff0eafdcdf0]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74d6d)[0x7ff0eada8d6d]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x7d86)[0x7ff0eadb0ef6]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x8006b)[0x7ff0eadb406b]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8dba)[0x7ff0eafdcdba]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74d6d)[0x7ff0eada8d6d]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x7d86)[0x7ff0eadb0ef6]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x8006b)[0x7ff0eadb406b]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8dba)[0x7ff0eafdcdba]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74d6d)[0x7ff0eada8d6d]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x7d86)[0x7ff0eadb0ef6]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x8006b)[0x7ff0eadb406b]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8dba)[0x7ff0eafdcdba]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74d6d)[0x7ff0eada8d6d]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x7d86)[0x7ff0eadb0ef6]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x8006b)[0x7ff0eadb406b]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8dba)[0x7ff0eafdcdba]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74d6d)[0x7ff0eada8d6d]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x7d86)[0x7ff0eadb0ef6]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x8006b)[0x7ff0eadb406b]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74d6d)[0x7ff0eada8d6d]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x7d86)[0x7ff0eadb0ef6]
/lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0x8fb)[0x7ff0eaefee4b]
--- END LIBC BACKTRACE ---
